consul_user: "consul"
consul_group: "consul"
consul_install_dir: "/usr/bin"
consul_config_dir: "/etc/consul.d"
consul_data_dir: "/opt/consul"
consul_log_dir: "/var/log/consul"
consul_bind_address: "{{ subnet_ip }}"